project_id = "sqedesiqyadlrlidtvkj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = true
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
additional_redirect_urls = ["https://localhost:3000"]
external_email_enabled = true
external_phone_enabled = true
external_providers_enabled = true
anonymous_users_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.send-auth-email]
verify_jwt = false

[edge_runtime]
policy = "per_worker"
inspector_port = 8083